[project]
name = "ltx-pipelines"
version = "0.1.0"
description = "Pipelines implementation for Lightricks' LTX-2 model"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["ltx-core", "av", "tqdm", "pillow"]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"
